/**
 * A typed definition of wpapi.js
 * (Not autogenerated) 
 * 
 */
export {};
declare global {
    class WPAPI { 
    constructor(options : exa.WPAPI_Options);
  
    registerRoute( namespace: string, restBase: string) : exa.WPRequest 
    registerRoute( namespace: string, restBase: string, options: any): exa.WPRequest 
  
  //   menus() : exa.WPRequest
    posts() : exa.WPRequest
    media() : exa.WPRequest
  } 
  
  export namespace exa {
    class WPAPI_Options {
        public endpoint : string;
    }
  
    interface WPRequest extends Promise<any> {
        constructor(options : {
            endpoint: String, 
            transport: Object,
            username?:String,
            password?:String,
            nonce?:String})
        
        toString() : string
        setPathPart(level : Number,val: Number|string) : WPRequest
        validatePath() : WPRequest
        param(props:String|Object, value:String|Number|Array<any>): WPRequest
  
        // convenience
        slug(slug : string): WPRequest;
        author(author : string): WPRequest;
        status(status : string|Array<string>): WPRequest;
        search(query : string): WPRequest;
        before(date : Date): WPRequest;
        after(date : Date): WPRequest;
        sticky(isSticky : boolean): WPRequest;
        id(id : number): WPRequest;
        categories(id : number): WPRequest;
  
        // paging & sorting
        perPage(perPage : number): WPRequest
        page(page : number): WPRequest;
        order(ord : string): WPRequest;
        orderby(str : string): WPRequest;
    }
  }
  }
  