/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/state-tunnel';
import {
  EventEmitter,
} from '@stencil/core';
import {
  ExaHeraldBreakpoint,
} from '.';
import {
  ExaHeraldBreakpoint as ExaHeraldBreakpoint2,
} from './index';
import {
  ExaMedia,
  ExaPost,
} from './global/ExaMedia';
import {
  ExaMenuDirection,
  ExaMenuDropdownStyle,
  ExaMenuFontSize,
  ExaMenuLinkColor,
} from './components/exa-menu/exa-menu-style';


export namespace Components {

  interface ExaBlock {}
  interface ExaBlockAttributes extends StencilHTMLAttributes {}

  interface ExaBreakpointListener {}
  interface ExaBreakpointListenerAttributes extends StencilHTMLAttributes {
    'onBreakpointChanged'?: (event: CustomEvent<ExaHeraldBreakpoint>) => void;
  }

  interface ExaBreakpoint {
    'all': boolean;
    'breakpoint': ExaHeraldBreakpoint;
    'desktop': boolean;
    'mobile': boolean;
    'tablet': boolean;
    'xl': boolean;
  }
  interface ExaBreakpointAttributes extends StencilHTMLAttributes {
    'all'?: boolean;
    'breakpoint'?: ExaHeraldBreakpoint;
    'desktop'?: boolean;
    'mobile'?: boolean;
    'tablet'?: boolean;
    'xl'?: boolean;
  }

  interface ExaCardTeaser {
    'imgsrc': string;
    'subhead': string;
    'title': string;
    'url': string;
  }
  interface ExaCardTeaserAttributes extends StencilHTMLAttributes {
    'imgsrc'?: string;
    'subhead'?: string;
    'title'?: string;
    'url'?: string;
  }

  interface ExaContainer {
    'breakpoint': ExaHeraldBreakpoint;
  }
  interface ExaContainerAttributes extends StencilHTMLAttributes {
    'breakpoint'?: ExaHeraldBreakpoint;
  }

  interface ExaFootnotes {
    'modified': string;
    'postid': string;
    'published': string;
    'shareheadline': string;
    'shareurl': string;
  }
  interface ExaFootnotesAttributes extends StencilHTMLAttributes {
    'modified'?: string;
    'postid'?: string;
    'published'?: string;
    'shareheadline'?: string;
    'shareurl'?: string;
  }

  interface ExaHomeAboveFold {
    'breakpoint': ExaHeraldBreakpoint;
  }
  interface ExaHomeAboveFoldAttributes extends StencilHTMLAttributes {
    'breakpoint'?: ExaHeraldBreakpoint;
  }

  interface ExaMenuButton {
    'active': boolean;
  }
  interface ExaMenuButtonAttributes extends StencilHTMLAttributes {
    'active'?: boolean;
  }

  interface ExaMenuDropdown {
    'menuItems': Array<any>;
    'posts': Array<ExaPost>;
    'subhead': string;
    'title': string;
    'url': string;
  }
  interface ExaMenuDropdownAttributes extends StencilHTMLAttributes {
    'menuItems'?: Array<any>;
    'posts'?: Array<ExaPost>;
    'subhead'?: string;
    'title'?: string;
    'url'?: string;
  }

  interface ExaMenuItem {
    'category': number;
    'childmenuitems': Array<any>;
    'debug': boolean;
    'dropdownStyle': ExaMenuDropdownStyle;
    'iconClass': string;
    'title': string;
    'url': string;
  }
  interface ExaMenuItemAttributes extends StencilHTMLAttributes {
    'category'?: number;
    'childmenuitems'?: Array<any>;
    'debug'?: boolean;
    'dropdownStyle'?: ExaMenuDropdownStyle;
    'iconClass'?: string;
    'title'?: string;
    'url'?: string;
  }

  interface ExaMenu {
    'debug': boolean;
    'menuDirection': ExaMenuDirection;
    'menuDropdown': ExaMenuDropdownStyle;
    'menuFontSize': ExaMenuFontSize;
    'menuId': number;
    'menuLinkColor': ExaMenuLinkColor;
    'tag_id': string;
    'title': string;
  }
  interface ExaMenuAttributes extends StencilHTMLAttributes {
    'debug'?: boolean;
    'menuDirection'?: ExaMenuDirection;
    'menuDropdown'?: ExaMenuDropdownStyle;
    'menuFontSize'?: ExaMenuFontSize;
    'menuId'?: number;
    'menuLinkColor'?: ExaMenuLinkColor;
    'tag_id'?: string;
    'title'?: string;
  }

  interface ExaNameplate {
    'breakpoint': ExaHeraldBreakpoint;
    'columns': number;
    'primaryMenu': number;
    'searchQuery': string;
    'secondaryMenu': number;
    'socialMenu': number;
  }
  interface ExaNameplateAttributes extends StencilHTMLAttributes {
    'breakpoint'?: ExaHeraldBreakpoint;
    'columns'?: number;
    'primaryMenu'?: number;
    'searchQuery'?: string;
    'secondaryMenu'?: number;
    'socialMenu'?: number;
  }

  interface ExaNextIn {
    'postid': string;
    'tag_id': string;
    'title': string;
    'url': string;
  }
  interface ExaNextInAttributes extends StencilHTMLAttributes {
    'postid'?: string;
    'tag_id'?: string;
    'title'?: string;
    'url'?: string;
  }

  interface ExaPublishTimeMeta {
    'modified': string;
    'published': string;
  }
  interface ExaPublishTimeMetaAttributes extends StencilHTMLAttributes {
    'modified'?: string;
    'published'?: string;
  }

  interface ExaRoot {
    'pageWidth': number;
  }
  interface ExaRootAttributes extends StencilHTMLAttributes {
    'pageWidth'?: number;
  }

  interface ExaSearchForm {}
  interface ExaSearchFormAttributes extends StencilHTMLAttributes {}

  interface ExaSocialButton {
    'classname': string;
    'description': string;
    'shareurl': string;
    'title': string;
  }
  interface ExaSocialButtonAttributes extends StencilHTMLAttributes {
    'classname'?: string;
    'description'?: string;
    'shareurl'?: string;
    'title'?: string;
  }

  interface ExaTeaser {
    'media': ExaMedia;
    'post': ExaPost;
  }
  interface ExaTeaserAttributes extends StencilHTMLAttributes {
    'media'?: ExaMedia;
    'post'?: ExaPost;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ExaBlock': Components.ExaBlock;
    'ExaBreakpointListener': Components.ExaBreakpointListener;
    'ExaBreakpoint': Components.ExaBreakpoint;
    'ExaCardTeaser': Components.ExaCardTeaser;
    'ExaContainer': Components.ExaContainer;
    'ExaFootnotes': Components.ExaFootnotes;
    'ExaHomeAboveFold': Components.ExaHomeAboveFold;
    'ExaMenuButton': Components.ExaMenuButton;
    'ExaMenuDropdown': Components.ExaMenuDropdown;
    'ExaMenuItem': Components.ExaMenuItem;
    'ExaMenu': Components.ExaMenu;
    'ExaNameplate': Components.ExaNameplate;
    'ExaNextIn': Components.ExaNextIn;
    'ExaPublishTimeMeta': Components.ExaPublishTimeMeta;
    'ExaRoot': Components.ExaRoot;
    'ExaSearchForm': Components.ExaSearchForm;
    'ExaSocialButton': Components.ExaSocialButton;
    'ExaTeaser': Components.ExaTeaser;
  }

  interface StencilIntrinsicElements {
    'exa-block': Components.ExaBlockAttributes;
    'exa-breakpoint-listener': Components.ExaBreakpointListenerAttributes;
    'exa-breakpoint': Components.ExaBreakpointAttributes;
    'exa-card-teaser': Components.ExaCardTeaserAttributes;
    'exa-container': Components.ExaContainerAttributes;
    'exa-footnotes': Components.ExaFootnotesAttributes;
    'exa-home-above-fold': Components.ExaHomeAboveFoldAttributes;
    'exa-menu-button': Components.ExaMenuButtonAttributes;
    'exa-menu-dropdown': Components.ExaMenuDropdownAttributes;
    'exa-menu-item': Components.ExaMenuItemAttributes;
    'exa-menu': Components.ExaMenuAttributes;
    'exa-nameplate': Components.ExaNameplateAttributes;
    'exa-next-in': Components.ExaNextInAttributes;
    'exa-publish-time-meta': Components.ExaPublishTimeMetaAttributes;
    'exa-root': Components.ExaRootAttributes;
    'exa-search-form': Components.ExaSearchFormAttributes;
    'exa-social-button': Components.ExaSocialButtonAttributes;
    'exa-teaser': Components.ExaTeaserAttributes;
  }


  interface HTMLExaBlockElement extends Components.ExaBlock, HTMLStencilElement {}
  var HTMLExaBlockElement: {
    prototype: HTMLExaBlockElement;
    new (): HTMLExaBlockElement;
  };

  interface HTMLExaBreakpointListenerElement extends Components.ExaBreakpointListener, HTMLStencilElement {}
  var HTMLExaBreakpointListenerElement: {
    prototype: HTMLExaBreakpointListenerElement;
    new (): HTMLExaBreakpointListenerElement;
  };

  interface HTMLExaBreakpointElement extends Components.ExaBreakpoint, HTMLStencilElement {}
  var HTMLExaBreakpointElement: {
    prototype: HTMLExaBreakpointElement;
    new (): HTMLExaBreakpointElement;
  };

  interface HTMLExaCardTeaserElement extends Components.ExaCardTeaser, HTMLStencilElement {}
  var HTMLExaCardTeaserElement: {
    prototype: HTMLExaCardTeaserElement;
    new (): HTMLExaCardTeaserElement;
  };

  interface HTMLExaContainerElement extends Components.ExaContainer, HTMLStencilElement {}
  var HTMLExaContainerElement: {
    prototype: HTMLExaContainerElement;
    new (): HTMLExaContainerElement;
  };

  interface HTMLExaFootnotesElement extends Components.ExaFootnotes, HTMLStencilElement {}
  var HTMLExaFootnotesElement: {
    prototype: HTMLExaFootnotesElement;
    new (): HTMLExaFootnotesElement;
  };

  interface HTMLExaHomeAboveFoldElement extends Components.ExaHomeAboveFold, HTMLStencilElement {}
  var HTMLExaHomeAboveFoldElement: {
    prototype: HTMLExaHomeAboveFoldElement;
    new (): HTMLExaHomeAboveFoldElement;
  };

  interface HTMLExaMenuButtonElement extends Components.ExaMenuButton, HTMLStencilElement {}
  var HTMLExaMenuButtonElement: {
    prototype: HTMLExaMenuButtonElement;
    new (): HTMLExaMenuButtonElement;
  };

  interface HTMLExaMenuDropdownElement extends Components.ExaMenuDropdown, HTMLStencilElement {}
  var HTMLExaMenuDropdownElement: {
    prototype: HTMLExaMenuDropdownElement;
    new (): HTMLExaMenuDropdownElement;
  };

  interface HTMLExaMenuItemElement extends Components.ExaMenuItem, HTMLStencilElement {}
  var HTMLExaMenuItemElement: {
    prototype: HTMLExaMenuItemElement;
    new (): HTMLExaMenuItemElement;
  };

  interface HTMLExaMenuElement extends Components.ExaMenu, HTMLStencilElement {}
  var HTMLExaMenuElement: {
    prototype: HTMLExaMenuElement;
    new (): HTMLExaMenuElement;
  };

  interface HTMLExaNameplateElement extends Components.ExaNameplate, HTMLStencilElement {}
  var HTMLExaNameplateElement: {
    prototype: HTMLExaNameplateElement;
    new (): HTMLExaNameplateElement;
  };

  interface HTMLExaNextInElement extends Components.ExaNextIn, HTMLStencilElement {}
  var HTMLExaNextInElement: {
    prototype: HTMLExaNextInElement;
    new (): HTMLExaNextInElement;
  };

  interface HTMLExaPublishTimeMetaElement extends Components.ExaPublishTimeMeta, HTMLStencilElement {}
  var HTMLExaPublishTimeMetaElement: {
    prototype: HTMLExaPublishTimeMetaElement;
    new (): HTMLExaPublishTimeMetaElement;
  };

  interface HTMLExaRootElement extends Components.ExaRoot, HTMLStencilElement {}
  var HTMLExaRootElement: {
    prototype: HTMLExaRootElement;
    new (): HTMLExaRootElement;
  };

  interface HTMLExaSearchFormElement extends Components.ExaSearchForm, HTMLStencilElement {}
  var HTMLExaSearchFormElement: {
    prototype: HTMLExaSearchFormElement;
    new (): HTMLExaSearchFormElement;
  };

  interface HTMLExaSocialButtonElement extends Components.ExaSocialButton, HTMLStencilElement {}
  var HTMLExaSocialButtonElement: {
    prototype: HTMLExaSocialButtonElement;
    new (): HTMLExaSocialButtonElement;
  };

  interface HTMLExaTeaserElement extends Components.ExaTeaser, HTMLStencilElement {}
  var HTMLExaTeaserElement: {
    prototype: HTMLExaTeaserElement;
    new (): HTMLExaTeaserElement;
  };

  interface HTMLElementTagNameMap {
    'exa-block': HTMLExaBlockElement
    'exa-breakpoint-listener': HTMLExaBreakpointListenerElement
    'exa-breakpoint': HTMLExaBreakpointElement
    'exa-card-teaser': HTMLExaCardTeaserElement
    'exa-container': HTMLExaContainerElement
    'exa-footnotes': HTMLExaFootnotesElement
    'exa-home-above-fold': HTMLExaHomeAboveFoldElement
    'exa-menu-button': HTMLExaMenuButtonElement
    'exa-menu-dropdown': HTMLExaMenuDropdownElement
    'exa-menu-item': HTMLExaMenuItemElement
    'exa-menu': HTMLExaMenuElement
    'exa-nameplate': HTMLExaNameplateElement
    'exa-next-in': HTMLExaNextInElement
    'exa-publish-time-meta': HTMLExaPublishTimeMetaElement
    'exa-root': HTMLExaRootElement
    'exa-search-form': HTMLExaSearchFormElement
    'exa-social-button': HTMLExaSocialButtonElement
    'exa-teaser': HTMLExaTeaserElement
  }

  interface ElementTagNameMap {
    'exa-block': HTMLExaBlockElement;
    'exa-breakpoint-listener': HTMLExaBreakpointListenerElement;
    'exa-breakpoint': HTMLExaBreakpointElement;
    'exa-card-teaser': HTMLExaCardTeaserElement;
    'exa-container': HTMLExaContainerElement;
    'exa-footnotes': HTMLExaFootnotesElement;
    'exa-home-above-fold': HTMLExaHomeAboveFoldElement;
    'exa-menu-button': HTMLExaMenuButtonElement;
    'exa-menu-dropdown': HTMLExaMenuDropdownElement;
    'exa-menu-item': HTMLExaMenuItemElement;
    'exa-menu': HTMLExaMenuElement;
    'exa-nameplate': HTMLExaNameplateElement;
    'exa-next-in': HTMLExaNextInElement;
    'exa-publish-time-meta': HTMLExaPublishTimeMetaElement;
    'exa-root': HTMLExaRootElement;
    'exa-search-form': HTMLExaSearchFormElement;
    'exa-social-button': HTMLExaSocialButtonElement;
    'exa-teaser': HTMLExaTeaserElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
