/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  ExaFootnotesPost as ExaFootnotesPost
} from './components/exa-footnotes/exa-footnotes-post/exa-footnotes-post';

declare global {
  interface HTMLExaFootnotesPostElement extends ExaFootnotesPost, HTMLStencilElement {
  }
  var HTMLExaFootnotesPostElement: {
    prototype: HTMLExaFootnotesPostElement;
    new (): HTMLExaFootnotesPostElement;
  };
  interface HTMLElementTagNameMap {
    "exa-footnotes-post": HTMLExaFootnotesPostElement;
  }
  interface ElementTagNameMap {
    "exa-footnotes-post": HTMLExaFootnotesPostElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "exa-footnotes-post": JSXElements.ExaFootnotesPostAttributes;
    }
  }
  namespace JSXElements {
    export interface ExaFootnotesPostAttributes extends HTMLAttributes {
      imgsrc?: string;
      subhead?: string;
      title?: string;
      url?: string;
    }
  }
}


import {
  ExaCommentsFootnotes as ExaFootnotes
} from './components/exa-footnotes/exa-footnotes';

declare global {
  interface HTMLExaFootnotesElement extends ExaFootnotes, HTMLStencilElement {
  }
  var HTMLExaFootnotesElement: {
    prototype: HTMLExaFootnotesElement;
    new (): HTMLExaFootnotesElement;
  };
  interface HTMLElementTagNameMap {
    "exa-footnotes": HTMLExaFootnotesElement;
  }
  interface ElementTagNameMap {
    "exa-footnotes": HTMLExaFootnotesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "exa-footnotes": JSXElements.ExaFootnotesAttributes;
    }
  }
  namespace JSXElements {
    export interface ExaFootnotesAttributes extends HTMLAttributes {
      postid?: string;
      tag_id?: string;
      title?: string;
      url?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
